### ISSUE TITLE
Cant position the image properly.

### ISSUE THREAD

**Issue by din1122** [AlbanCrepel/vue-displacement-slideshow#12]
It seems that Width:100% and height:100% would fix it but it doesn't. on mobile, my images are looking good. but on Desktop they get cut on edges. top and left mostly.

Please help me fix it. Check out the problem on section 5 www.dinashkenazi.com

**Comment by AlbanCrepel** [comment]
Hi @din1122 ! First, I am very happy to see you using the component :v: 
Yes I see the problem here. Actually, the images are displayed as we would use `background-size:cover` in CSS. So the aspect ratio of the image is preserved... 
I guess you will have to set the size of your section or to set the scale of your images according to the viewport.
Do you think that it would be better to set a prop like `background-size` to `contain` or `cover` to manually set the behavior of the images displayed ?

**Comment by AlbanCrepel** [comment]
Hi @din1122 ! Sorry it has been quite a long time since you opened this issue. But I am glad to tell you that you can now tell the component not to preserve the aspect ratio of the images by setting the prop `preserveAspectRatio` to `false`. You can have a look at the doc in the Readme for more information. This should fix your problem 😉
